In [46]:
import numpy as np 
import random
import pprint


#CARGAR MATRIZ INCIDENCIA RANDOM, CONTROLO EL % DE CONEXIONES(1)
def matrizIncidencia(cantNodos:int, probabilidad:float):
    matriz=np.zeros((cantNodos,cantNodos),int)
    for fila in range(cantNodos):
        for columna in range(cantNodos):
            if fila==columna:
                matriz[fila][columna]=0
            elif random.random()<probabilidad:
                #CONTROLO CANT DE 1
                matriz[fila][columna]=1
    return matriz

In [47]:
#DE MATRIZ DE INCIDENCIA HAGO LISTA DE CONEXIONES
def listaConexiones(matriz:np.ndarray):
    lista=[]
    cantNodos=matriz.shape[0]
    for fila in range(cantNodos):
        columna=-1
        conexion=False
        for elemento in matriz[fila]:
            #ME EMPIEZO A MOVER X LAS COLUMNAS
            columna+=1
            if elemento==1:
                lista.append((fila,columna))
                conexion=True
        if conexion==False:
            #NODO SIN ARISTAS
            lista.append((fila,None))
    return lista

In [48]:
class TDAGrafo:
    def __init__(self,listaConexiones):
        self.grafo=dict()
        self.contador_aristas = 0
        self.listaADiccionario(listaConexiones)
        self.cardinalMayorMenor()

    #DE LISTA DE CONEXIONES A DICCIONARIO
    def listaADiccionario(self,listaConexiones):
    
        for element1,element2 in listaConexiones:
            if element2 !=None:

                self.grafo.setdefault(element1,[]) #ESTRUCTURA
                if element2 not in self.grafo[element1]: #NO DUPLICADOS
                    self.grafo[element1].append(element2)

                self.grafo.setdefault(element2,[]) #ESTRUCTURA
                if element1 not in self.grafo[element2]: #NO DUPLICADOS
                    self.grafo[element2].append(element1)
                
                    self.contador_aristas += 1

            else:
                self.grafo.setdefault(element1,[])

    
    #ARREGLO DE CARDINALIDADES DE MAYOR A MENOR
    def cardinalMayorMenor(self):
        cardinalidades=[]
        for nodo,conectados in self.grafo.items():
            cardinalidades.append((nodo,len(conectados)))
        cardinalidades.sort(key=lambda x:x[1], reverse=True)
        return cardinalidades

In [49]:
def mvc(grafo):
    #TODOS LOS NODOS QUE CUMPLEN CON RECORRER TODOS LAS ARISTAS
    vertexCover=[]
    aristasVisitadas=[]
    while len(aristasVisitadas)<grafo.contador_aristas:
        for nodo in grafo.cardinalMayorMenor():
            for elemento in grafo.grafo[nodo[0]]:
                if {nodo[0],elemento} not in aristasVisitadas:
                        aristasVisitadas.append({nodo[0],elemento})
                        if nodo[0] not in vertexCover:
                            vertexCover.append(nodo[0])
    return vertexCover         

In [50]:
cantNodos=5
probabilidad=0.3
m=matrizIncidencia(cantNodos,probabilidad)

m = np.array([
    [0,1,0,0,0,0,1,1,0,1,0,0],
    [1,0,1,0,0,0,0,0,0,0,1,0],
    [0,1,0,1,0,0,0,0,0,0,1,0],
    [0,0,1,0,1,0,0,0,0,0,1,1],
    [0,0,0,1,0,1,0,1,0,0,0,1],
    [0,0,0,0,1,0,1,0,0,0,0,0],
    [1,0,0,0,0,1,0,1,0,0,0,0],
    [1,0,0,0,1,1,1,0,1,0,0,0],
    [0,0,0,0,0,0,0,1,0,1,0,1],
    [1,0,0,0,0,0,0,0,1,0,1,0],
    [0,1,1,1,0,0,0,0,0,1,0,0],
    [0,0,0,1,1,0,0,0,1,0,0,0]])


print(m)
print()

l=listaConexiones(m)
print(l)
print()

grafo=TDAGrafo(l)


pretty_print = pprint.PrettyPrinter()
pretty_print.pprint(grafo.grafo)
resultado=mvc(grafo)
print()
print(resultado)


[[0 1 0 0 0 0 1 1 0 1 0 0]
 [1 0 1 0 0 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 0 1 1]
 [0 0 0 1 0 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 1 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 1 0 1 0]
 [0 1 1 1 0 0 0 0 0 1 0 0]
 [0 0 0 1 1 0 0 0 1 0 0 0]]

[(0, 1), (0, 6), (0, 7), (0, 9), (1, 0), (1, 2), (1, 10), (2, 1), (2, 3), (2, 10), (3, 2), (3, 4), (3, 10), (3, 11), (4, 3), (4, 5), (4, 7), (4, 11), (5, 4), (5, 6), (6, 0), (6, 5), (6, 7), (7, 0), (7, 4), (7, 5), (7, 6), (7, 8), (8, 7), (8, 9), (8, 11), (9, 0), (9, 8), (9, 10), (10, 1), (10, 2), (10, 3), (10, 9), (11, 3), (11, 4), (11, 8)]

{0: [1, 6, 7, 9],
 1: [0, 2, 10],
 2: [1, 3, 10],
 3: [2, 4, 10, 11],
 4: [3, 5, 7, 11],
 5: [4, 6, 7],
 6: [0, 5, 7],
 7: [0, 4, 6, 5, 8],
 8: [7, 9, 11],
 9: [0, 8, 10],
 10: [1, 2, 3, 9],
 11: [3, 4, 8]}

[7, 0, 10, 3, 4, 1, 6, 9, 11]
